{
  "formatVersion": "1.1",
  "component": {
    "group": "com.msd",
    "module": "msd.sdk",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "msd.sdk-0.0.1.aar",
          "url": "msd.sdk-0.0.1.aar",
          "size": 107250,
          "sha512": "c5fa1b760511a4b0cda264b807bcd8171fbdb816a170cce6a7f7bf9872b20ee1e1edbd9d97f74efb04623f7aa5ee7eb4ab2f628769b1784ab014350f82da9e2e",
          "sha256": "15532cf112d54efc2d2db9967ce98d8e4d73421eb9121c27a29c9340fe5c9062",
          "sha1": "c1a7b7cc20a1618fdd905526def6ed448b9e045e",
          "md5": "82153edca73b481a4a0210d78f557aa1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "msd.sdk-0.0.1.aar",
          "url": "msd.sdk-0.0.1.aar",
          "size": 107250,
          "sha512": "c5fa1b760511a4b0cda264b807bcd8171fbdb816a170cce6a7f7bf9872b20ee1e1edbd9d97f74efb04623f7aa5ee7eb4ab2f628769b1784ab014350f82da9e2e",
          "sha256": "15532cf112d54efc2d2db9967ce98d8e4d73421eb9121c27a29c9340fe5c9062",
          "sha1": "c1a7b7cc20a1618fdd905526def6ed448b9e045e",
          "md5": "82153edca73b481a4a0210d78f557aa1"
        }
      ]
    }
  ]
}
