{
  "formatVersion": "1.1",
  "component": {
    "group": "com.msd",
    "module": "msd.sdk",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "msd.sdk-0.0.1.aar",
          "url": "msd.sdk-0.0.1.aar",
          "size": 108578,
          "sha512": "b7f86c92fc7ecf37e8549c6adb2fafce6d7baf3315602e7f7528a58abbdd1d12f1e635a1e29ea07d2ad964ae1625b46b7da6adf2efc1df41ee0d3bd4400f91c0",
          "sha256": "e76ddd31005eb19f5f0bee87e1024b82ff9e11bc0ed1390ab66c4af08f59edf9",
          "sha1": "68669d79e68cfb7e87d1e434676b538af5a54a28",
          "md5": "facb6164b4d490687c27cd9abde9be91"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "msd.sdk-0.0.1.aar",
          "url": "msd.sdk-0.0.1.aar",
          "size": 108578,
          "sha512": "b7f86c92fc7ecf37e8549c6adb2fafce6d7baf3315602e7f7528a58abbdd1d12f1e635a1e29ea07d2ad964ae1625b46b7da6adf2efc1df41ee0d3bd4400f91c0",
          "sha256": "e76ddd31005eb19f5f0bee87e1024b82ff9e11bc0ed1390ab66c4af08f59edf9",
          "sha1": "68669d79e68cfb7e87d1e434676b538af5a54a28",
          "md5": "facb6164b4d490687c27cd9abde9be91"
        }
      ]
    }
  ]
}
