{
  "formatVersion": "1.1",
  "component": {
    "group": "com.msd",
    "module": "msd.sdk",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "msd.sdk-0.0.1.aar",
          "url": "msd.sdk-0.0.1.aar",
          "size": 108305,
          "sha512": "a5ce5115daa05b2270c2bac4e744e7f6fe48dfd548189eb7a5369bc0b5b098fbc9351c849728c58c523ef7363f3b8bebfdfc9d811f449cb937733c7624e092fb",
          "sha256": "d1b283c369e324261e31228a9b9bf3fac1c5ca7f9262edb00d6bc4005bc61f6a",
          "sha1": "191eeda048608265754d799b9ab93e288d59b129",
          "md5": "b63e930cd5acd452706a44b4712e141b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "msd.sdk-0.0.1.aar",
          "url": "msd.sdk-0.0.1.aar",
          "size": 108305,
          "sha512": "a5ce5115daa05b2270c2bac4e744e7f6fe48dfd548189eb7a5369bc0b5b098fbc9351c849728c58c523ef7363f3b8bebfdfc9d811f449cb937733c7624e092fb",
          "sha256": "d1b283c369e324261e31228a9b9bf3fac1c5ca7f9262edb00d6bc4005bc61f6a",
          "sha1": "191eeda048608265754d799b9ab93e288d59b129",
          "md5": "b63e930cd5acd452706a44b4712e141b"
        }
      ]
    }
  ]
}
